version: '3.8'

services:
  sandbox:
    container_name: v2r
    build:
      context: .
    volumes:
      - ./:/app
    # env_file:
    #   - ./.env
    ports:
      - 5000:5000
    # networks:
    #   - raslib-net
    entrypoint: CompileDaemon --build="go build main.go" --command="./main"